# WHAT DOES THIS FILE DO: Auto-generates a markdown report summarizing the code plus its reliability and security analysis.


# =========== FUNCTION ===========
# ROLE: appends one check's score line, and up to a few of its issues, to the doc being built
def _append_check_section(doc: str, check_name: str, check_result: dict, max_issues: int) -> str:
    ''' every check gets a "- **Name:** score/100" line, then a few issue bullets if there are any '''

    title = check_name.replace("_", " ").title()
    doc += f"\n- **{title}:** {check_result.get('score', 0)}/100"

    # FLOW-1: only checks that actually carry an "issues" list get sub-bullets — not every layer's breakdown has one
    issues = check_result.get("issues") or []
    for issue in issues[:max_issues]:
        doc += f"\n  - {issue.get('detail', 'Issue detected')}"

    return doc
# =========== FUNCTION ===========


# =========== FUNCTION ===========
# ROLE: builds the full markdown documentation for a piece of code from its reliability + security reports
def generate_documentation(code: str, reliability_report: dict, security_report: dict) -> str:
    ''' one section for the code itself, one for reliability, one for security, each with a per-check breakdown '''

    reliability_breakdown = reliability_report.get("breakdown", {})
    security_breakdown = security_report.get("breakdown", {})

    doc = f"""# Code Analysis Report

## Generated Code
```python
{code}
```

## Reliability Analysis
- **Score:** {reliability_report.get('score', 0)}/100
- **Status:** {reliability_report.get('label', 'Unknown')}

### Checks Performed
"""

    # FLOW-1: reliability checks — up to 3 issues per check
    for check_name, check_result in reliability_breakdown.items():
        doc = _append_check_section(doc, check_name, check_result, max_issues=3)

    doc += f"\n\n## Security Analysis\n- **Score:** {security_report.get('score', 0)}/100\n- **Status:** {security_report.get('label', 'Unknown')}\n\n### Security Checks\n"

    # FLOW-2: security checks — up to 2 issues per check, security reports tend to be noisier per-check
    for check_name, check_result in security_breakdown.items():
        doc = _append_check_section(doc, check_name, check_result, max_issues=2)

    doc += "\n\n---\n*Generated by Shinrai — Trust the code you ship.*"

    return doc
# =========== FUNCTION ===========
